import './globals.css'
import { ToastContainer } from 'react-toastify'
// import 'react-toastify/dist/react-toastify'
import { Inter } from 'next/font/google'
import UserProvider from './context/user'
import CartProvider from './context/cart'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'eBay Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ToastContainer />
        <UserProvider>
          <CartProvider>
          {children}
          </CartProvider>
        </UserProvider>
      </body>
    </html>
  )
}
